backend:
  name: git-gateway
  branch: main

media_folder: media
public_folder: /media

collections:
  - label: 'Homepage'
    name: 'homepage'
    files:
    - label: 'Content'
      name: 'content'
      editor:
        preview: false
      file: '_src/index.md'
      fields:
        - { label: Title, name: title, widget: string }
        - { label: Lede, name: lede, widget: string, required: false }
        - { label: Content, name: body, widget: markdown }
  - label: 'Settings'
    name: 'settings'
    files:
      - label: Site
        name: site
        editor:
          preview: false
        file: '_src/_data/site.json'
        fields:
          - { label: 'Site Title', name: title, widget: string }
          - { label: 'Site Description', name: description, widget: string, required: false }
          - { label: 'URL', name: url, widget: string, required: false }
          - { label: 'Author', name: author, widget: string }
          - { label: 'Job Title', name: role, widget: string, required: false }
          - { label: 'Email Address', name: email, widget: string, required: false }
          - label: "Social Links"
            name: "socials"
            widget: "list"
            summary: '{{fields.site}}'
            fields:
              - {label: 'Label', name: site, widget: string }
              - {label: 'Icon', name: icon, widget: image, choose_url: false, required: false }
              - {label: 'URL', name: url, widget: string }
