backend:
  name: git-gateway
  branch: master 

media_folder: media
public_folder: /media

{% if site.url %}
site_url: {{ site.url }}
{% endif %}

collections:
  - label: Homepage
    files:
    - label: Homepage
      name: site
      file: index.md
      name: homapage
      create: true
      fields:
        - { label: Title, name: title, widget: string }
        - { label: Date, name: date, widget: datetime, required: false }
        - { label: Tags, name: tags, widget: list, default: ["post"] }
        - { label: Content, name: body, widget: markdown }
  - label: Settings
    name: settings
    files:
      - label: Site
        name: site
        file: _data/site.json
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Description, name: description, widget: string, required: false }
          - { label: Language, name: language, widget: string }
          - { label: URL, name: url, widget: string, required: false }