backend:
  name: git-gateway
  branch: main

media_folder: _src/img
public_folder: /img

collections:
  - label: 'Homepage'
    name: 'homepage'
    files:
    - label: 'Content'
      name: 'content'
      editor:
        preview: false
      file: '_src/index.md'
      fields:
        - { label: Title, name: title, widget: string }
        - { label: Lede, name: lede, widget: string, required: false }
        - { label: Content, name: body, widget: markdown }
  - label: 'Settings'
    name: 'settings'
    files:
      - label: Site
        name: site
        editor:
          preview: false
        file: '_src/_data/site.json'
        fields:
          - { label: 'Site Title', name: title, widget: string }
          - { label: 'Site Description', name: description, widget: string, required: false }
          - { label: 'URL', name: url, widget: string }
          - { label: 'Author', name: author, widget: string }
          - { label: 'Job Title', name: role, widget: string }
          - { label: 'Email Address', name: email, widget: string }
          - { label: 'Copyright', name: copyright, widget: string, required: false }
          - label: "Social Links"
            name: "socials"
            widget: "list"
            summary: '{{fields.site}}'
            fields:
              - {label: 'Label', name: site, widget: string }
              - {label: 'Icon', name: icon, widget: image, choose_url: false, required: false }
              - {label: 'URL', name: url, widget: string }
          - label: "Microcopy"
            name: "microcopy"
            widget: "object"
            collapsed: false
            summary: '{{fields.name}}'
            fields:
              - {label: "Page Not Found", name: "notfound", widget: "string", default: "404: Page not found" }
              - label: "Contact Form"
                name: "contact"
                widget: "object"
                fields: 
                  - {label: "Contact Button", name: "contact", widget: "string", default: "Contact me" }
                  - {label: "Success", name: "success", widget: "string", default: "Successfully submitted." }
                  - {label: "Error", name: "error", widget: "string", default: "Sorry, there was an error." }
          - label: "Shortlinks"
            name: "shortlinks"
            widget: "list"
            summary: '{{fields.short}}: {{fields.url}}'
            fields:
              - {label: "Shortlink", name: short, widget: string}
              - {label: "URL", name: url, widget: string}
