backend:
  name: git-gateway
  branch: main

media_folder: media
public_folder: /media

collections:
  - label: 'Homepage'
    name: 'homepage'
    files:
    - label: 'Content'
      name: 'content'
      editor:
        preview: false
      file: '_src/index.md'
      fields:
        - { label: Title, name: title, widget: string }
        - { label: Content, name: body, widget: markdown }
  - label: 'Settings'
    name: 'settings'
    files:
      - label: Site
        name: site
        editor:
          preview: false
        file: '_src/_data/site.json'
        fields:
          - { label: Title, name: title, widget: string, required: false }
          - { label: Lede, name: lede, widget: string, required: false }
          - { label: Description, name: description, widget: string, required: false }
          - { label: Language, name: language, widget: string }
          - { label: URL, name: url, widget: string, required: false }